### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by darkhandz** [jhw-dev/RxSwift-CN#10]
GettingStarted.md

`一些序列是有限的而另一些是无线的` 应为 `一些序列是有限的而另一些是无限的`

**Comment by Edison-Hsu** [comment]
已经修改，感谢指出错误

**Comment by darkhandz** [comment]
GettingStarted.md

**处置包(Dispose Bags)**
Dispose bags之于RX被用来返回类似ARC行为
当一个 DisposeBag 被销毁， 它会在每一个已加入的可处置对象中调用 dispose 方法。
因为他没有 dispose 方法，所以不允许在目标上显示调用 dispose 方法。如果需要马上清理，我们仅需创建一个新的dipose bag。

`因为他没有 dispose 方法`这句的`他`我觉得可以改成 `它`, 这里应该是指disposeBag对象没有直接的dispose()方法, 要清理里面的订阅, 需要创建一个新的disposeBag对象.

不少`显示`麻烦检查一下, 应该是`显式`

感谢各位辛苦翻译.

**Comment by Edison-Hsu** [comment]
已经修改，感谢再次指出错误
