### ISSUE TITLE
我觉得应该加入ReactiveX的中文文档

### ISSUE THREAD

**Issue by Insofan** [jhw-dev/RxSwift-CN#9]
rx系列是一整套体系的，光写上RxSwift的会让人看不懂，真正看过一遍ReactiveX文档会让人理解rx的概念，swift只是它的一个延伸很多api都是rx系列通用的。提供你个地址
https://www.gitbook.com/book/mcxiaoke/rxdocs

**Comment by Edison-Hsu** [comment]
这系列翻译完全是从 [RxSwift](https://github.com/ReactiveX/RxSwift/tree/2.5.0/Documentation) 当时的版本摘录出来进行翻译。

这个翻译项目存在的意识是对那些希望快速上手 RxSwift 但是又不习惯看英文的国内开发者，给予一定的文档支持。

RxSwift 中不只是延伸了 Rx 基本的概念，在 RxCocoa 中，例如 Variable，Driver Unit 等，都并不包含于 Rx 基本概念中。

所以，学习 Rx 和 RxSwift 是一个持续和多方面的过程，你说的地址，当年学习 Rx 的时候已经看过，是学习 Rx 通用概念的好材料。大家各司其职，开发者各取所需即可。
